### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by acgpiano** [unknownproject/Silent_Hill_Homecoming#2]
Hi, thanks for doing this. I use your patch and didn't change the strings.str file, my string file is Chinese,  And it does not work in-game. Can you tell me how to use my own string file? thx

**Comment by acgpiano** [comment]
Such as this:
`[IDS_SHELL_WALK]行走

[IDS_SHELL_AUDIO]音频设置
[IDS_SHELL_AUDIO_TITLE]音频设置
[IDS_SHELL_VIDEO]视频设置
[IDS_SHELL_VIDEO_TITLE]视频设置
[IDS_SHELL_RESOLUTION]分辨率
[IDS_SHELL_REFRESH]刷新频率
[IDS_SHELL_QUALITY]图象质量
[IDS_SHELL_QUALITY_MEDIUM]中等
[IDS_SHELL_QUALITY_HIGH]高
[IDS_SHELL_CONTROLLER_CONFIG_TITLE_PC]控制设置
[IDS_SHELL_CONTROLLER_CONFIG_PC]控制设置
[IDS_SHELL_USE_MOUSE]使用鼠标以及键盘
[IDS_SHELL_USE_CONTROLLER]使用手柄
[IDS_SHELL_MOUSE_CONTROLS_TITLE]鼠标与键盘
[IDS_SHELL_CONTROLLER_CONTROLS_TITLE]手柄
[IDS_SHELL_MOUSE_SENSITIVITY]鼠标灵敏度

###SHELL STRINGS ###
[IDS_SHELL_PRESS_START_PC]按任意键以开始
[IDS_SHELL_PRESS_START_PS3]按Start键以开始
[IDS_SHELL_PRESS_START_XBOX360]按Start键以开始

[IDS_SHELL_ACCEPT]接受
[IDS_SHELL_BACK]返回
[IDS_SHELL_CHECKPOINT]记录点
[IDS_SHELL_USE]使用
[IDS_SHELL_EQUIP]装备
[IDS_SHELL_SELECT]选择
[IDS_SHELL_YES]是
[IDS_SHELL_NO]否
[IDS_SHELL_OK]好的
[IDS_SHELL_OFF]关闭
[IDS_SHELL_ON]打开
[IDS_SHELL_SCROLL]文件
[IDS_SHELL_ZOOM]地图缩放
[IDS_SHELL_EXIT]退出游戏
[IDS_SHELL_NEXT]下一个
[IDS_SHELL_LOADING_SCREEN_TEXT]读 取 中`

**Comment by unknownproject** [comment]
Well. Like the other unicode languages 
(as not officially supported by the game) 
its required a global resource modification and installation. 
Actually a font modification.
Installation process can be found in:
https://github.com/unknownproject/Silent_Hill_Homecoming/blob/master/Patches/ReadMe.txt
under "HOW TO USE NEW RESOURCE MANAGER" section. 
If .str files are just modifications for original english files it should work as default language 
(they need to be replaced).
PS. I'm working with original files only. 
I will add anything I can find by myself. 
I have limits only by my own fantasy/needs or will.
